# Generated by Django 3.2.7 on 2021-10-01 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercise_exercise_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answered',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.alternative'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alternative',
            name='is_right',
            field=models.BooleanField(default=False, verbose_name='Afirmativa correta?'),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='letter',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Letra da Altern.'),
        ),
        migrations.AlterField(
            model_name='alternative',
            name='text',
            field=models.CharField(max_length=150, verbose_name='Texto da Altern.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='exercise_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.exercisegroup', verbose_name='Lista de Exercício'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='order_num',
            field=models.CharField(max_length=20, verbose_name='Num. de Ordem'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sub_title',
            field=models.CharField(max_length=100, verbose_name='Sub.Titulo'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Titulo'),
        ),
    ]
