# Generated by Django 3.2.7 on 2021-10-02 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211001_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='api.alternative', verbose_name='Escolha do usuário'),
        ),
    ]
