# Generated by Django 3.2.7 on 2021-10-02 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_answer_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alternative', verbose_name='Escolha do usuário'),
        ),
    ]
