# Generated by Django 3.2.7 on 2021-10-02 12:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_answer_answered'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('exercise', 'answered', 'user')},
        ),
    ]
